CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE TABLE "MensagensOutbox" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "MensagemId" uuid NOT NULL,
        "Tipo" character varying(100) NOT NULL,
        "Conteudo" jsonb NOT NULL,
        "OcorridoEm" timestamp with time zone NOT NULL,
        "CorrelacaoId" character varying(64),
        "PublicadaEm" timestamp with time zone,
        "Tentativas" integer NOT NULL,
        "UltimoErro" character varying(2000),
        CONSTRAINT "PK_MensagensOutbox" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(100) NOT NULL,
        "Email" character varying(200) NOT NULL,
        "SenhaHash" character varying(200) NOT NULL,
        "Perfil" character varying(20) NOT NULL,
        "Status" character varying(30) NOT NULL,
        "TentativasFalhas" integer NOT NULL,
        "BloqueadoAte" timestamp with time zone,
        "CriadoEm" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE TABLE "Eventos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrganizadorId" integer NOT NULL,
        "Titulo" character varying(150) NOT NULL,
        "Descricao" character varying(4000) NOT NULL,
        "Local" character varying(150) NOT NULL,
        "Cidade" character varying(100) NOT NULL,
        "DataInicio" timestamp with time zone NOT NULL,
        "Publicado" boolean NOT NULL,
        "CriadoEm" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Eventos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Eventos_Usuarios_OrganizadorId" FOREIGN KEY ("OrganizadorId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "TokenHash" character varying(64) NOT NULL,
        "Familia" uuid NOT NULL,
        "CriadoEm" timestamp with time zone NOT NULL,
        "ExpiraEm" timestamp with time zone NOT NULL,
        "UsadoEm" timestamp with time zone,
        "RevogadoEm" timestamp with time zone,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE TABLE "Pedidos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "EventoId" integer NOT NULL,
        "Status" character varying(30) NOT NULL,
        "Total" numeric(10,2) NOT NULL,
        "CriadoEm" timestamp with time zone NOT NULL,
        "ExpiraEm" timestamp with time zone NOT NULL,
        "PagoEm" timestamp with time zone,
        "FinalizadoEm" timestamp with time zone,
        "CodigoPagamento" character varying(64),
        CONSTRAINT "PK_Pedidos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Pedidos_Eventos_EventoId" FOREIGN KEY ("EventoId") REFERENCES "Eventos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Pedidos_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE TABLE "Setores" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EventoId" integer NOT NULL,
        "Nome" character varying(80) NOT NULL,
        "Preco" numeric(10,2) NOT NULL,
        "Capacidade" integer NOT NULL,
        "Ocupados" integer NOT NULL,
        CONSTRAINT "PK_Setores" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Setores_Ocupados" CHECK ("Ocupados" >= 0 AND "Ocupados" <= "Capacidade"),
        CONSTRAINT "FK_Setores_Eventos_EventoId" FOREIGN KEY ("EventoId") REFERENCES "Eventos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE TABLE "Ingressos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PedidoId" integer NOT NULL,
        "SetorId" integer NOT NULL,
        "Codigo" character varying(32) NOT NULL,
        "PrecoPago" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_Ingressos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Ingressos_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Ingressos_Setores_SetorId" FOREIGN KEY ("SetorId") REFERENCES "Setores" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE TABLE "ItensPedido" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PedidoId" integer NOT NULL,
        "SetorId" integer NOT NULL,
        "NomeSetor" character varying(80) NOT NULL,
        "Quantidade" integer NOT NULL,
        "PrecoUnitario" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_ItensPedido" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_ItensPedido_Quantidade" CHECK ("Quantidade" > 0),
        CONSTRAINT "FK_ItensPedido_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ItensPedido_Setores_SetorId" FOREIGN KEY ("SetorId") REFERENCES "Setores" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_Eventos_OrganizadorId" ON "Eventos" ("OrganizadorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_Eventos_Publicado_DataInicio" ON "Eventos" ("Publicado", "DataInicio");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE UNIQUE INDEX "IX_Ingressos_Codigo" ON "Ingressos" ("Codigo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_Ingressos_PedidoId" ON "Ingressos" ("PedidoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_Ingressos_SetorId" ON "Ingressos" ("SetorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_ItensPedido_PedidoId" ON "ItensPedido" ("PedidoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_ItensPedido_SetorId" ON "ItensPedido" ("SetorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE UNIQUE INDEX "IX_MensagensOutbox_MensagemId" ON "MensagensOutbox" ("MensagemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_MensagensOutbox_Pendentes" ON "MensagensOutbox" ("Id") WHERE "PublicadaEm" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_Pedidos_EventoId" ON "Pedidos" ("EventoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_Pedidos_ExpiraEm" ON "Pedidos" ("ExpiraEm") WHERE "Status" = 'AguardandoPagamento';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_Pedidos_UsuarioId_CriadoEm" ON "Pedidos" ("UsuarioId", "CriadoEm");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_RefreshTokens_Familia" ON "RefreshTokens" ("Familia");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE UNIQUE INDEX "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_RefreshTokens_UsuarioId" ON "RefreshTokens" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_Setores_EventoId" ON "Setores" ("EventoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE UNIQUE INDEX "IX_Usuarios_Email" ON "Usuarios" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    CREATE INDEX "IX_Usuarios_Perfil_Status" ON "Usuarios" ("Perfil", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916190500_Inicial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260916190500_Inicial', '10.0.11');
    END IF;
END $EF$;
COMMIT;

